### ISSUE TITLE
Hidden fields in a repeater not hiding on load

### ISSUE THREAD

**Issue by thely** [graham73may/bolt-conditional-fields#2]
Normal, non-repeater fields with conditions will auto-hide the conditional field as normal. Conditional fields inside a repeater will show all fields by default until one of them is selected, and then showing/hiding works as normal. When a page/entry is saved with the condition-changing select field set to a non-(none) value, there's an extra caveat - all fields will show by default, but if you continue to select the saved value, the show/hide behavior doesn't trigger. You have to select a _different_ field for it to work.

Ex: I have a repeater field that can conditionally be text, an image, or a video. When I load the page, all fields will show, even though they are set to be hidden unless selected. When I select one of them, the rest will hide as expected. If I save with "video" selected in my first repeater set and reload the page, all the fields will display. If I select "video" to try and trigger show/hide behavior, nothing changes, but if I select "text" or "image," it'll show only text/image, and afterwards I can select "video" again.

(I've got one other issue I found, but I've got a few things to do and then I'll post that as well)

**Comment by graham73may** [comment]
Can you post your contenttypes.yml with the conditions in? 

If I've understood what you've said, mine is doing what you're expecting... I think. 

Even so, I can make a quick bolt instance using your config and have a test. 

(There were some slight changes to repeaters in 3.2.0+, the extension code may need to be tweaked since the update)

**Comment by thely** [comment]
This is the contentType in question. The `body` and `has_body` fields are tests, and work as expected, while everything under `stream_field` is still acting up.
```
works:
    name: Works
    singular_name: Work
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        date:
            type: date
            label: Date Released
        instrumentation:
            type: text
        image:
            type: image
        program_note:
            type: textarea
            label: Program Note
        has_body:
            type: select
            values: ['default', 'yes', 'no']
        body:
            type: text
            condition:
                field: has_body
                operator: '='
                show: true
                value: ['yes']
        stream_field:
            label: "Stream Field"
            type: repeater
            fields:
                block_type:
                    label: "Select a block"
                    type: select
                    values: {'text': "Rich text",'video': "Video",'image': "Image",'callout': "Callout"}
                item_text:
                    label: "Rich text"
                    type: html
                    condition:
                        field: block_type
                        operator: '='
                        show: true
                        value: ['text']
                item_video:
                    label: "Video"
                    type: video
                    condition:
                        field: block_type
                        operator: '='
                        show: true
                        value: ['video']
                item_image:
                    label: "Image"
                    type: image
                    condition:
                        field: block_type
                        operator: '='
                        show: true
                        value: ['image']
                item_callout:
                    label: "Callout text"
                    type: text
                    condition:
                        field: block_type
                        operator: '='
                        show: true
                        value: ['callout']
                item_callout_paragraph:
                    label: "Callout paragraph"
                    type: textarea
                    condition:
                        field: block_type
                        operator: '='
                        show: true
                        value: ['callout']
```
