### ISSUE TITLE
[WIP] Multiple conditions

### ISSUE THREAD

**Issue by graham73may** [graham73may/bolt-conditional-fields#4]
Accept multiple conditions to hide/show a field. 

Example config:
```
condition:
[
    field: field_one
    operator: '='
    show: true
    value: [ 'page' , 'this', 'that']
] , [
    field: field_two
    operator: '='
    show: true
    value: [ 'page' , 'this', 'that']
]
```
