### ISSUE TITLE
[WIP] Add support for < and > conditions

### ISSUE THREAD

**Issue by graham73may** [graham73may/bolt-conditional-fields#5]
Add less than or greater than conditions

Example config
```
condition:
    field: count
    operator: '<'
    show: true
    value: 5
```
